@PrisonersDilemma_Api_HostAddress = http://kube-dev.mindbox.ru/p-dilemma
# @PrisonersDilemma_Api_HostAddress = http://localhost:5246
@Bearer_Token = Bearer your_jwt_token_here
@X-MasterKey = super-secret-master-key-2024
@Client_ID = client-001
@Client_Secret = a7b9c3d4e5f6789012345678901234567890abcd
@Player_ID_1 = 3fe9447c-840f-46d0-ac68-8551379b3350
@Player_ID_2 = eb5d8061-4951-47fb-a52c-5c4eabc141ac
@Session_ID = cc6ccca9-4f7f-4314-bc00-cae93768eb4d

### Health Check - Liveness
GET {{PrisonersDilemma_Api_HostAddress}}/health/live
Accept: application/json

### Health Check - Readiness
GET {{PrisonersDilemma_Api_HostAddress}}/health/ready
Accept: application/json

### Auth - Get JWT Token (OAuth2 Client Credentials Flow)
POST {{PrisonersDilemma_Api_HostAddress}}/api/auth/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id={{Client_ID}}&client_secret={{Client_Secret}}&scope=game:read game:write

### Auth - Get User Info (requires JWT token)
GET {{PrisonersDilemma_Api_HostAddress}}/api/auth/user
Authorization: {{Bearer_Token}}
Accept: application/json

### Game - Start New Game
POST {{PrisonersDilemma_Api_HostAddress}}/api/game/start
Content-Type: application/json
Authorization: {{Bearer_Token}}
X-MasterKey: {{X-MasterKey}}

{
  "playerId": "{{Player_ID_1}}",
  "playerName": "Bob"
}

### Game - Get Game Info
GET {{PrisonersDilemma_Api_HostAddress}}/api/game/{{Session_ID}}
Authorization: {{Bearer_Token}}
Accept: application/json
X-MasterKey: {{X-MasterKey}}

### Game - Get Round Info
GET {{PrisonersDilemma_Api_HostAddress}}/api/game/{{Session_ID}}/round/1
Authorization: {{Bearer_Token}}
Accept: application/json
X-MasterKey: {{X-MasterKey}}

### Game - Submit Choice (Cooperate)
POST {{PrisonersDilemma_Api_HostAddress}}/api/game/choice
Content-Type: application/json
Authorization: {{Bearer_Token}}
X-MasterKey: {{X-MasterKey}}

{
  "sessionId": "{{Session_ID}}",
  "playerId": "{{Player_ID_2}}",
  "roundNumber": 3,
  "choice": "Cooperate"
}

### Game - Submit Choice (Defect)
POST {{PrisonersDilemma_Api_HostAddress}}/api/game/choice
Content-Type: application/json
Authorization: {{Bearer_Token}}

{
  "sessionId": "{{Session_ID}}",
  "playerId": "{{Player_ID}}",
  "roundNumber": 1,
  "choice": "Defect"
}
